// ── Dolphin Lynxi · TypeScript data ─────────────────────────────────────────

export interface Dataset {
  id: string; name: string; icon: string; image: string;
  scene: string; arm: 'single' | 'dual'; modality: string[];
  episodes: number; duration: number; frames: number; resolution: string;
  device: string; vendor: string;
  price: number; rating: number; downloads: number; publishedAt: string;
  tags: string[]; hot?: boolean; new?: boolean; description: string;
}

export interface Task {
  id: string; title: string; icon: string;
  type: 'collect' | 'verify' | 'label' | 'custom';
  client: string; scene: string;
  reward: number; rewardUnit: string; target: number; progress: number;
  deadline: string; device: string; level: string; status: string;
  requirements: string[]; description: string;
}

export interface Device {
  id: string; name: string; icon: string; image: string; group: string;
  category: string; price: number; priceSuffix?: string; status: string;
  hot?: boolean; new?: boolean; features: string[]; desc: string;
}

export interface Course {
  id: string; title: string; icon: string;
  level: string; format: string; duration: string;
  price: number; priceLabel?: string;
  enrolled: number; rating: number; includes: string[]; desc: string;
}

export interface Skill {
  id: string; name: string; icon: string; image: string; scene: string;
  model: string; basedOn: string; successRate: number; latency: number;
  price: number; downloads: number; rating: number; license: string;
  requires: string; desc: string;
}

export interface OssDataset {
  id: string; name: string; org: string; type: string; image: string;
  license: string; scale: string; metric: string; tags: string[];
  desc: string; href: string;
}

// ── Datasets ──────────────────────────────────────────────────────────────────
export const datasets: Dataset[] = [
  { id:'DLX-DS-1001', name:'拿铁拉花·意式咖啡机制作', icon:'☕', image:'assets/datasets-feat/coffee-latte-art.jpg',
    scene:'餐饮', arm:'single', modality:['RGB-D','ARM-Joint','Force'],
    episodes:120, duration:2.7, frames:288000, resolution:'640×480@30',
    device:'Dolphin-Arm', vendor:'海豚自营', price:4800, rating:4.9, downloads:312, publishedAt:'2026-03-12',
    tags:['柔性液体','VLA适用','ACT 兼容'], hot:true, new:false,
    description:'参考 ALOHA static_coffee 协议设计，覆盖意式机萃取、奶泡打发、拉花郁金香/桃心/天鹅三式。' },
  { id:'DLX-DS-1002', name:'叠 T 恤·标准两折法', icon:'👕', image:'assets/datasets-feat/fold-tshirt.jpg',
    scene:'家庭服务', arm:'dual', modality:['RGB','RGB-D','ARM-Joint'],
    episodes:200, duration:3.9, frames:700000, resolution:'720P@50',
    device:'Dolphin-Dual', vendor:'海豚自营', price:9800, rating:4.95, downloads:528, publishedAt:'2026-02-08',
    tags:['双臂协同','柔性物体','ACT 经典任务','LeRobot v3'], hot:true, new:false,
    description:'沿用 ALOHA static_fold_shirt 协议，50Hz 双臂同步采集。纯棉/雪纺/亚麻三种面料 × 5 种花色。' },
  { id:'DLX-DS-1003', name:'PCB 贴片元件抓取·0402/0603 封装', icon:'🔧', image:'assets/datasets-feat/pcb-smt.jpg',
    scene:'工业制造', arm:'single', modality:['RGB-D','ARM-Joint','Tactile'],
    episodes:600, duration:6.7, frames:1440000, resolution:'1080P@60',
    device:'Dolphin-Arm+Pro', vendor:'精选合集', price:38000, rating:4.85, downloads:76, publishedAt:'2026-01-18',
    tags:['工业级','精密','力觉反馈','SMT 标准'], hot:false, new:false,
    description:'SMT 流水线场景采集，0402/0603/0805 三种封装。60Hz 高帧率配合亚毫米级定位。' },
  { id:'DLX-DS-1004', name:'快递分拣·四区流水线', icon:'📦', image:'assets/datasets-feat/parcel-sort.jpg',
    scene:'物流仓储', arm:'single', modality:['RGB','ARM-Joint'],
    episodes:400, duration:2.8, frames:300000, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'众包采集', price:5600, rating:4.7, downloads:245, publishedAt:'2026-03-02',
    tags:['物流','高节拍','众包'], new:false, hot:false,
    description:'分拨中心实景采集，信封/小盒/不规则三类，按 A/B/C/D 四区分拣 SOP。' },
  { id:'DLX-DS-1005', name:'桌面物品整理·杂乱场景', icon:'🗂️', image:'assets/datasets-feat/desk-tidy.jpg',
    scene:'家庭服务', arm:'single', modality:['RGB-D','ARM-Joint'],
    episodes:300, duration:10.0, frames:1080000, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'海豚自营', price:6200, rating:4.82, downloads:198, publishedAt:'2026-03-20',
    tags:['长程任务','开放场景','VLA适用','LIBERO 风格'], new:true, hot:true,
    description:'100 张家庭真实桌面 × 3 种凌乱度，每集含 8-15 个物体的归位策略。含语言指令标注。' },
  { id:'DLX-DS-1006', name:'夹娃娃机·公仔抓取', icon:'🎮', image:'assets/datasets-feat/claw-machine.jpg',
    scene:'娱乐零售', arm:'single', modality:['RGB','ARM-Joint'],
    episodes:200, duration:1.9, frames:210000, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'众包采集', price:2400, rating:4.6, downloads:167, publishedAt:'2026-04-05',
    tags:['趣味场景','视觉抓取','众包'], new:true,
    description:'6 家娃娃机店采集，弹簧式/重力式/铰链式三种爪型，成功/失败 60/40 均匀分布。' },
  { id:'DLX-DS-1007', name:'中药材分拣·四级形态识别', icon:'🌿', image:'assets/datasets-feat/herbs-sort.jpg',
    scene:'医疗医药', arm:'single', modality:['RGB-D','ARM-Joint'],
    episodes:200, duration:2.8, frames:300000, resolution:'1080P@30',
    device:'Dolphin-Arm+Pro', vendor:'精选合集', price:12800, rating:4.78, downloads:32, publishedAt:'2026-02-15',
    tags:['医药级','形态学','分类标准'], hot:false,
    description:'21 味常用中药材按"足/断/霉/虫"四级分拣，每味 200+ 样本，RGB-D 三视角对齐。' },
  { id:'DLX-DS-1008', name:'火锅涮毛肚·七上八下', icon:'🍲', image:'assets/datasets-feat/hotpot-tripe.jpg',
    scene:'餐饮', arm:'single', modality:['RGB-D','ARM-Joint','Force'],
    episodes:120, duration:0.8, frames:90000, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'海豚自营', price:3800, rating:4.88, downloads:412, publishedAt:'2026-01-22',
    tags:['柔性物体','力觉反馈','网红场景'], hot:true,
    description:'火锅连锁场景标准化采集，毛肚标准七上八下涮煮节奏（25s/次）。' },
  { id:'DLX-DS-1009', name:'便利店补货·先进先出', icon:'🛒', image:'assets/datasets-feat/convenience-restock.jpg',
    scene:'零售连锁', arm:'dual', modality:['RGB','ARM-Joint'],
    episodes:180, duration:6.0, frames:648000, resolution:'720P@30',
    device:'Dolphin-Dual', vendor:'精选合集', price:18800, rating:4.81, downloads:58, publishedAt:'2026-02-28',
    tags:['零售','双臂','长程任务'], hot:false,
    description:'便利店货架场景采集，饮料/方便面/烟酒柜三类，FIFO 摆放策略已标注。' },
  { id:'DLX-DS-1010', name:'拧螺丝·M3-M8 多规格（含失败回退）', icon:'🔩', image:'assets/datasets-feat/screw-tighten.jpg',
    scene:'工业制造', arm:'single', modality:['RGB','ARM-Joint','Force','Tactile'],
    episodes:300, duration:2.5, frames:540000, resolution:'720P@60',
    device:'Dolphin-Arm+Pro', vendor:'海豚自营', price:28000, rating:4.92, downloads:134, publishedAt:'2025-12-08',
    tags:['工业级','力觉反馈','失败回退'], hot:true,
    description:'M3-M8 共 6 种规格 × 3 种材质 × 4 种力矩档位。含负样本 200 例。' },
  { id:'DLX-DS-1011', name:'叠毛巾·酒店四折法', icon:'🧻', image:'assets/datasets-feat/fold-towel.jpg',
    scene:'家庭服务', arm:'dual', modality:['RGB-D','ARM-Joint'],
    episodes:200, duration:2.5, frames:450000, resolution:'720P@50',
    device:'Dolphin-Dual', vendor:'众包采集', price:4600, rating:4.75, downloads:287, publishedAt:'2026-03-15',
    tags:['双臂','家政标准','众包'],
    description:'酒店保洁标准示范，四折/三折/卷筒三种法，含浴巾/面巾/方巾尺寸差异。' },
  { id:'DLX-DS-1012', name:'双臂开瓶盖·力觉反馈', icon:'🍾', image:'assets/datasets-feat/open-bottle.jpg',
    scene:'家庭服务', arm:'dual', modality:['RGB','ARM-Joint','Force','Tactile'],
    episodes:120, duration:0.7, frames:120000, resolution:'720P@50',
    device:'Dolphin-Dual', vendor:'海豚自营', price:5200, rating:4.86, downloads:198, publishedAt:'2026-04-02',
    tags:['双臂协同','力觉反馈','RoboSet 风格'], new:true,
    description:'20 种瓶盖形态，含失败回退策略 80 例。' },
  { id:'DLX-DS-1013', name:'手术器械递送·腔镜辅助', icon:'🏥', image:'assets/datasets-feat/surgical-tool.jpg',
    scene:'医疗医药', arm:'single', modality:['RGB-D','ARM-Joint','Force'],
    episodes:80, duration:1.0, frames:216000, resolution:'1080P@60',
    device:'Dolphin-Arm+Med', vendor:'精选合集', price:88000, rating:4.91, downloads:9, publishedAt:'2026-01-05',
    tags:['医疗级','无菌环境','精细操作'],
    description:'微创外科场景采集，14 种器械按递送规范，60Hz 高帧率。【医疗器械合规备案中】' },
  { id:'DLX-DS-1014', name:'奶茶杯封口贴', icon:'🧋', image:'assets/datasets-feat/bubble-tea-seal.jpg',
    scene:'餐饮', arm:'single', modality:['RGB','ARM-Joint'],
    episodes:150, duration:0.6, frames:67500, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'众包采集', price:2800, rating:4.72, downloads:356, publishedAt:'2026-03-28',
    tags:['连锁餐饮','高节拍','众包'],
    description:'茶饮连锁门店采集，异形杯/平口杯/带料杯三类，平均节拍 < 15s/杯。' },
  { id:'DLX-DS-1015', name:'电子产品装箱·EVA 内衬', icon:'📱', image:'assets/datasets-feat/eva-packaging.jpg',
    scene:'工业制造', arm:'dual', modality:['RGB-D','ARM-Joint','Force'],
    episodes:200, duration:5.0, frames:540000, resolution:'1080P@30',
    device:'Dolphin-Dual+Pro', vendor:'精选合集', price:22000, rating:4.83, downloads:41, publishedAt:'2026-02-12',
    tags:['工业级','双臂','SOP 标准'],
    description:'TWS 耳机装箱场景采集，4 种 SKU 包装 SOP，双臂 EVA 内衬精确对位。' },
  { id:'DLX-DS-1016', name:'整理床铺·拉床单铺被罩', icon:'🛏️', image:'assets/datasets-feat/make-bed.jpg',
    scene:'家庭服务', arm:'dual', modality:['RGB-D','ARM-Joint'],
    episodes:120, duration:6.0, frames:648000, resolution:'720P@30',
    device:'Dolphin-Dual', vendor:'海豚自营', price:7200, rating:4.79, downloads:156, publishedAt:'2026-03-08',
    tags:['双臂','大尺寸柔性','长程任务'],
    description:'1.5m × 2m 床面，纯棉/真丝/磨毛三种面料，涵盖角部包裹、拍打舒展全流程。' },
  { id:'DLX-DS-1017', name:'插花·东方禅意三才法', icon:'🌸', image:'assets/datasets-feat/ikebana.jpg',
    scene:'艺术文创', arm:'single', modality:['RGB-D','ARM-Joint','Force'],
    episodes:80, duration:2.7, frames:288000, resolution:'1080P@30',
    device:'Dolphin-Arm', vendor:'众包采集', price:3600, rating:4.94, downloads:67, publishedAt:'2026-04-10',
    tags:['艺术','创意','小众高质'], new:true,
    description:'三位非遗传承人示范，含天/地/人三主枝插法。' },
  { id:'DLX-DS-1018', name:'擦桌子·咖啡渍清理', icon:'🧽', image:'assets/datasets-feat/clean-table.jpg',
    scene:'清洁服务', arm:'single', modality:['RGB','ARM-Joint','Force'],
    episodes:300, duration:2.9, frames:315000, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'海豚自营', price:3200, rating:4.71, downloads:234, publishedAt:'2026-03-18',
    tags:['清洁','力觉反馈','RoboSet 兼容'],
    description:'120 张桌面 × 5 种污渍程度，螺旋/直线/Z 形三种擦拭轨迹对照。' },
  { id:'DLX-DS-1019', name:'乐高积木拼装·8 步法', icon:'🧱', image:'assets/datasets-feat/lego-build.jpg',
    scene:'教育玩具', arm:'dual', modality:['RGB-D','ARM-Joint'],
    episodes:120, duration:3.7, frames:396000, resolution:'720P@30',
    device:'Dolphin-Dual', vendor:'众包采集', price:4400, rating:4.86, downloads:178, publishedAt:'2026-02-22',
    tags:['双臂','长程任务','教育'],
    description:'15 套乐高经典系列拆解，标注 8 步内可完成的组装序列，适合训练长程 VLA。' },
  { id:'DLX-DS-1020', name:'水果切块·苹果橙子分块', icon:'🍎', image:'assets/datasets-feat/cut-fruit.jpg',
    scene:'餐饮', arm:'single', modality:['RGB-D','ARM-Joint','Force'],
    episodes:150, duration:2.1, frames:225000, resolution:'720P@30',
    device:'Dolphin-Arm+Knife', vendor:'海豚自营', price:5800, rating:4.74, downloads:89, publishedAt:'2026-03-25',
    tags:['餐饮','刀具操作','安全标注'],
    description:'4 种水果 × 2 种刀型，标注安全姿态包络，含刀具夹持安全检查点。' },
  { id:'DLX-DS-1021', name:'眼镜片擦拭·防雾布', icon:'👓', image:'assets/datasets-feat/clean-glasses.jpg',
    scene:'精细服务', arm:'single', modality:['RGB','ARM-Joint','Force','Tactile'],
    episodes:100, duration:0.5, frames:108000, resolution:'720P@60',
    device:'Dolphin-Arm+Pro', vendor:'众包采集', price:2200, rating:4.68, downloads:124, publishedAt:'2026-04-08',
    tags:['精细操作','力觉反馈','小众'], new:true,
    description:'树脂/玻璃/防蓝光三种镜片擦拭压力曲线对比，60Hz 高帧率监测。' },
  { id:'DLX-DS-1022', name:'书本归位·按颜色分类', icon:'📚', image:'assets/datasets-feat/book-sort.jpg',
    scene:'教育', arm:'single', modality:['RGB','ARM-Joint'],
    episodes:150, duration:1.0, frames:112500, resolution:'720P@30',
    device:'Dolphin-Arm', vendor:'众包采集', price:1800, rating:4.62, downloads:203, publishedAt:'2026-03-30',
    tags:['分类','入门友好','LIBERO 风格'],
    description:'50 本书 × 6 种颜色分类，适合入门 VLA 训练，含 instruction-tuned 文本指令。' },
  { id:'DLX-DS-1023', name:'端茶壶倒茶·茶具递送', icon:'🍵', image:'assets/datasets-feat/hotel-tray.jpg',
    scene:'餐饮', arm:'dual', modality:['RGB-D','ARM-Joint','Force'],
    episodes:150, duration:2.5, frames:450000, resolution:'720P@50',
    device:'Dolphin-Dual', vendor:'海豚自营', price:9600, rating:4.88, downloads:47, publishedAt:'2026-03-05',
    tags:['双臂协同','茶艺','ACT 经典任务'], new:true,
    description:'参考 Mobile ALOHA pour_wine 双臂协议设计，含端壶/倾注/收杯三段动作。' },
  { id:'DLX-DS-1024', name:'双臂折叠快递箱', icon:'📮', image:'assets/datasets-feat/fold-box.jpg',
    scene:'物流仓储', arm:'dual', modality:['RGB','ARM-Joint','Force'],
    episodes:200, duration:4.2, frames:450000, resolution:'720P@30',
    device:'Dolphin-Dual', vendor:'海豚自营', price:6800, rating:4.83, downloads:132, publishedAt:'2026-04-15',
    tags:['双臂','物流','VLA适用'], new:true,
    description:'4 种尺寸纸箱折叠/封装全流程，含胶带粘贴控制力，单集 70-80s。' },
];

// ── Tasks ─────────────────────────────────────────────────────────────────────
export const tasks: Task[] = [
  { id:'TASK-2001', title:'中式面点·甩面动作专项采集', icon:'🍜',
    type:'collect', client:'某连锁餐饮龙头', scene:'餐饮',
    reward:8000, rewardUnit:'积分/集', target:500, progress:142,
    deadline:'2026-06-30', device:'Dolphin-Dual', level:'中级', status:'active',
    requirements:['双臂同步','三视角','含力觉','面团形变捕获'],
    description:'复现兰州拉面师傅甩面动作，要求双臂同步 ±5ms 内，力觉数据完整。' },
  { id:'TASK-2002', title:'家庭洗碗机装盘策略', icon:'🍽️',
    type:'collect', client:'某头部白电品牌', scene:'家庭服务',
    reward:5000, rewardUnit:'积分/集', target:800, progress:312,
    deadline:'2026-07-20', device:'Dolphin-Arm', level:'入门', status:'active',
    requirements:['RGB-D','含碗碟变形','3 种洗碗机机型'],
    description:'采集真实家庭 5 类餐具按机型空间最优装盘策略。' },
  { id:'TASK-2003', title:'叠衣服数据集·二次众包校验', icon:'✅',
    type:'verify', client:'海豚平台', scene:'家庭服务',
    reward:50, rewardUnit:'积分/条', target:5000, progress:2840,
    deadline:'2026-05-31', device:'在线工具', level:'入门', status:'active',
    requirements:['标注经验','3 类衣型识别','可远程'],
    description:'对 DLX-DS-1002 数据集动作完成度 0-100 评分 + 失败原因 5 选 1 标签。' },
  { id:'TASK-2004', title:'【独家大单】3C 工厂上下料 SOP', icon:'🏭',
    type:'custom', client:'某 TOP3 EMS 厂', scene:'工业制造',
    reward:1000000, rewardUnit:'总包', target:1, progress:0,
    deadline:'2026-08-15', device:'Dolphin-Dual+Pro', level:'大单', status:'active',
    requirements:['200 工位 SOP','3 班次覆盖','驻厂 4 周','保密协议'],
    description:'深圳/苏州两厂区联合采集，含 200 工位标准动作与 30+ 异常处理 case。仅向认证服务商开放投标。' },
  { id:'TASK-2005', title:'宠物喂食碗摆放', icon:'🐕',
    type:'collect', client:'某宠物智能家居品牌', scene:'家庭服务',
    reward:6000, rewardUnit:'积分/集', target:200, progress:38,
    deadline:'2026-06-10', device:'Dolphin-Arm', level:'中级', status:'active',
    requirements:['含猫狗干扰','地面湿滑场景','双视角'],
    description:'采集喂食碗摆放 + 宠物靠近时的避让策略。' },
  { id:'TASK-2006', title:'物体分割众包标注', icon:'🖍️',
    type:'label', client:'海豚自营 + 灵初智能', scene:'通用',
    reward:5, rewardUnit:'积分/帧', target:200000, progress:87600,
    deadline:'2026-07-31', device:'在线标注台', level:'入门', status:'active',
    requirements:['SAM 工具熟悉','像素级精度','质检合格率≥95%'],
    description:'为家庭场景 100 类常见物体打 mask，用于 VLA pre-training。' },
  { id:'TASK-2007', title:'中餐外卖打包盒装餐', icon:'🥡',
    type:'collect', client:'某外卖平台', scene:'餐饮',
    reward:7500, rewardUnit:'积分/集', target:300, progress:89,
    deadline:'2026-06-25', device:'Dolphin-Dual', level:'中级', status:'active',
    requirements:['含汤汁防洒','装盒 SOP','30 种菜品'],
    description:'复现真实外卖打包工序，涵盖主菜分装、汤品密封、餐具放入等。' },
  { id:'TASK-2008', title:'【询价】养老院助餐机器人定制', icon:'🍱',
    type:'custom', client:'某省连锁养老集团', scene:'医疗医药',
    reward:0, rewardUnit:'面议', target:1, progress:0,
    deadline:'2026-09-30', device:'Dolphin-Med', level:'大单', status:'active',
    requirements:['助餐安全规范','含失能老人辅助','医疗合规'],
    description:'20 家养老院驻场采集，预计 50 万级数据规模。需提交定制方案竞标。' },
  { id:'TASK-2009', title:'便利店扫码结账', icon:'💳',
    type:'collect', client:'头部便利连锁品牌', scene:'零售连锁',
    reward:4500, rewardUnit:'积分/集', target:400, progress:187,
    deadline:'2026-06-15', device:'Dolphin-Arm', level:'入门', status:'active',
    requirements:['含异形商品','POS 集成','多角度'],
    description:'采集 1500 SKU 的扫码/称重/支付全流程。' },
  { id:'TASK-2010', title:'【负样本】工业拧螺丝失败 case', icon:'⚠️',
    type:'verify', client:'海豚自营', scene:'工业制造',
    reward:80, rewardUnit:'积分/条', target:2000, progress:1142,
    deadline:'2026-05-28', device:'在线工具', level:'中级', status:'closing',
    requirements:['工业经验','失效模式 8 类','含原因标注'],
    description:'为 DLX-DS-1010 补充负样本，标注滑丝/打滑/错位/卡死等 8 种失效模式。' },
  { id:'TASK-2011', title:'插花·节庆主题创作', icon:'🎋',
    type:'collect', client:'花艺合作机构', scene:'艺术文创',
    reward:6800, rewardUnit:'积分/集', target:150, progress:27,
    deadline:'2026-07-15', device:'Dolphin-Arm', level:'高级', status:'active',
    requirements:['花艺师认证','含 6 大节庆','含艺术风格标签'],
    description:'春节/中秋/婚庆等 6 大节庆主题各 25 集，含 instruction-tuned 描述。' },
  { id:'TASK-2012', title:'【大单】物流暴力分拣压力测试', icon:'💥',
    type:'custom', client:'某头部物流企业', scene:'物流仓储',
    reward:800000, rewardUnit:'总包', target:1, progress:0,
    deadline:'2026-08-30', device:'Dolphin-Dual+Pro', level:'大单', status:'active',
    requirements:['极端场景','含损坏件采集','3 个分拨中心'],
    description:'为提升 VLA 鲁棒性，专项采集极端工况（包裹破损/标签污损/挤压形变）。' },
];

// ── Devices ───────────────────────────────────────────────────────────────────
export const devices: Device[] = [
  { id:'DEV-3015', name:'灵汐·轻量级机械臂', icon:'🦾',
    image:'assets/joycon.png', group:'teleop',
    category:'入门级桌面臂', price:1299, status:'现货', hot:true,
    features:['🦾 6 DOF 桌面臂 · 仅 0.8 kg','🕹️ Joy-Con 风格手柄遥操','✅ 已售 1000+ 套'],
    desc:'学生 / 创客入门首选，30 分钟上手开始数采。' },
  { id:'DEV-3006', name:'灵汐 EXO 主从外骨骼套件', icon:'🦾',
    image:'assets/search/EXO.png', group:'teleop',
    category:'EXO 外骨骼', price:8999, priceSuffix:'起', status:'现货', hot:true, new:true,
    features:['🦾 单 / 双臂 / 半身人形三形态','🧤 触觉手套 · 力反馈 ±5N（选配）','遥操延迟 < 5ms'],
    desc:'佩戴式外骨骼，动作 1:1 映射，已与多家头部本体厂商共建。' },
  { id:'DEV-3013', name:'灵汐 VR-Pro 手柄遥操套件', icon:'🎮',
    image:'assets/search/pico.jpeg', group:'teleop',
    category:'VR 手柄', price:2599, status:'现货', new:true,
    features:['Quest 3 / PICO 4 兼容','6 DOF 双手柄追踪','30 Hz 同步采集'],
    desc:'消费级 VR 头显 + Dolphin 适配器，万元内开始高质量数采。' },
  { id:'DEV-3014', name:'灵汐 Vision-XR · Vision Pro 套件', icon:'🥽',
    image:'assets/search/vision_pro.png', group:'teleop',
    category:'XR 沉浸遥操', price:6999, status:'预订', new:true,
    features:['Vision Pro 完美适配','眼动 + 手部追踪','支持双臂同步'],
    desc:'Vision Pro 眼动 + 手势遥操，精度比传统手柄高 3 倍。' },
];

// ── Courses ───────────────────────────────────────────────────────────────────
export const courses: Course[] = [
  { id:'EDU-4001', title:'零基础 3 天上手机械臂数采', icon:'🚀',
    level:'入门', format:'线下 · 上海', duration:'3 天 / 24h', price:999,
    enrolled:256, rating:4.92, includes:['Dolphin-Arm 套件','结业证书','5 小时云算力'],
    desc:'面向无任何机械臂经验的爱好者。第一天上手，第二天采集，第三天训出自己的小模型。' },
  { id:'EDU-4002', title:'ACT 模仿学习实战课', icon:'🎓',
    level:'中级', format:'在线 · 自助', duration:'12 课时', price:1999,
    enrolled:1820, rating:4.85, includes:['代码模板','5 个公开数据集','社区答疑'],
    desc:'LeRobot ACT 算法从原理到代码逐行讲解，配套海豚自营数据集训练。' },
  { id:'EDU-4003', title:'数据集质量评估师认证', icon:'📋',
    level:'高级', format:'线上+线下', duration:'4 周', price:3999,
    enrolled:124, rating:4.88, includes:['QC 工具','行业认证证书','优先接单资格'],
    desc:'海豚灵汐官方 QC 认证。考核通过后可接入平台数据集 QC 众包任务，按单结算。' },
  { id:'EDU-4004', title:'企业数采团队搭建陪跑（B 端）', icon:'🏢',
    level:'企业', format:'驻场咨询', duration:'8 周', price:0, priceLabel:'面议',
    enrolled:18, rating:5.0, includes:['团队招聘标准','SOP 模板','工具链交付'],
    desc:'为大 B 客户从 0 到 1 搭建内部数采团队，提供完整的招聘标准 / SOP / 工具链交付。' },
  { id:'EDU-4005', title:'VLA 大模型微调营', icon:'🔥',
    level:'专家', format:'线下集训', duration:'4 周', price:9999,
    enrolled:67, rating:4.94, includes:['π0/GR00T 微调代码','A100×8 算力','项目实战'],
    desc:'面向有 LeRobot 经验的工程师。结业可独立完成 VLA 模型行业微调。' },
];

// ── Skills ────────────────────────────────────────────────────────────────────
export const skills: Skill[] = [
  { id:'SKILL-5001', name:'叠衣服技能包 v2.1', icon:'👕', image:'assets/datasets-feat/fold-tshirt.jpg', scene:'家庭服务',
    model:'π0', basedOn:'DLX-DS-1002', successRate:89.2, latency:12,
    price:800, downloads:1256, rating:4.85, license:'商业付费', requires:'Dolphin-Dual',
    desc:'LeRobot π0 微调，4 种 T 恤面料 × 5 种花色全覆盖。20Hz 闭环推理。' },
  { id:'SKILL-5002', name:'拿铁拉花技能包', icon:'☕', image:'assets/datasets-feat/coffee-latte-art.jpg', scene:'餐饮',
    model:'ACT', basedOn:'DLX-DS-1001', successRate:92.4, latency:8,
    price:1200, downloads:487, rating:4.92, license:'商业付费', requires:'Dolphin-Arm + Espresso 模块',
    desc:'ACT v2 训练，郁金香式拉花成功率 92.4%。可落地于精品咖啡门店场景。' },
  { id:'SKILL-5003', name:'快递分拣技能包', icon:'📦', image:'assets/datasets-feat/parcel-sort.jpg', scene:'物流仓储',
    model:'GR00T-N1', basedOn:'DLX-DS-1004', successRate:96.8, latency:18,
    price:0, license:'Apache 2.0 开源', downloads:12480, rating:4.78, requires:'Dolphin-Arm 或兼容硬件',
    desc:'GR00T 微调，分拣 4 区任务成功率 96.8%。完全开源 + LeRobot 标准格式。' },
  { id:'SKILL-5004', name:'拧螺丝技能包 · 工业级', icon:'🔩', image:'assets/datasets-feat/screw-tighten.jpg', scene:'工业制造',
    model:'π0.5', basedOn:'DLX-DS-1010', successRate:98.2, latency:6,
    price:4800, downloads:64, rating:4.96, license:'企业 License', requires:'Dolphin-Arm+Pro · 含触觉皮肤',
    desc:'6 种规格 × 3 种材质 × 4 种力矩档。含失效模式自动重试。面向 EMS 工厂场景。' },
  { id:'SKILL-5005', name:'夹菜技能包 · 火锅毛肚', icon:'🍲', image:'assets/datasets-feat/hotpot-tripe.jpg', scene:'餐饮',
    model:'ACT', basedOn:'DLX-DS-1008', successRate:94.1, latency:10,
    price:600, downloads:723, rating:4.81, license:'商业付费', requires:'Dolphin-Arm',
    desc:'与头部火锅连锁联合调优，标准七上八下涮煮节奏，含汤面水汽鲁棒性增强。' },
  { id:'SKILL-5006', name:'便利店扫码结账', icon:'💳', image:'assets/skills/checkout-scan.jpg', scene:'零售连锁',
    model:'SmolVLA', basedOn:'DLX-DS-1009 + 内部数据', successRate:95.7, latency:14,
    price:0, license:'Apache 2.0 开源', downloads:3216, rating:4.74, requires:'Dolphin-Dual',
    desc:'SmolVLA 轻量推理（边缘可部署），1500 SKU 通用扫码模型。' },
  { id:'SKILL-5007', name:'快递箱折叠装箱', icon:'📮', image:'assets/datasets-feat/fold-box.jpg', scene:'物流仓储',
    model:'π0', basedOn:'DLX-DS-1024', successRate:91.3, latency:15,
    price:1500, downloads:142, rating:4.83, license:'商业付费', requires:'Dolphin-Dual',
    desc:'4 种尺寸纸箱通用，含胶带粘贴控制力。面向仓储自动化分拨中心场景。' },
  { id:'SKILL-5008', name:'插花技能包 · 三才法入门', icon:'🌸', image:'assets/datasets-feat/ikebana.jpg', scene:'艺术文创',
    model:'Diffusion Policy', basedOn:'DLX-DS-1017', successRate:76.5, latency:22,
    price:360, downloads:89, rating:4.68, license:'创意付费', requires:'Dolphin-Arm',
    desc:'入门款东方禅意三才插花，含天/地/人三主枝生成式策略。' },
];

// ── Open-source Datasets ──────────────────────────────────────────────────────
export const ossDatasets: OssDataset[] = [
  { id:'OXE', name:'Open X-Embodiment', org:'Google DeepMind + 22 实验室',
    type:'学术聚合', image:'assets/datasets/oxe.png',
    license:'Apache 2.0', scale:'100 万+ 轨迹', metric:'22 种机器人本体',
    tags:['VLA 预训练','跨本体','ImageNet 时刻'],
    desc:'机器人界的 ImageNet 时刻。22 家全球实验室数据聚合，RT-X / OpenVLA / Octo / π0 / RDT 几乎所有 VLA 都从这里预训练。',
    href:'https://robotics-transformer-x.github.io/' },
  { id:'AgiBotWorld', name:'AgiBot World Beta', org:'智元机器人 AgiBot',
    type:'商业开源', image:'assets/datasets/agibot.png',
    license:'CC BY-NC-SA 4.0', scale:'100 万+ 轨迹', metric:'2976 小时 · 100 台 G1',
    tags:['国产首发','人形机器人','大规模'],
    desc:'中国版 ImageNet 时刻。4000 平米数据工厂 + 100 台 G1，长程数据规模高出 OXE 10 倍。',
    href:'https://agibot-world.cn/' },
  { id:'DROID', name:'DROID', org:'Stanford + Berkeley + 13 实验室',
    type:'学术联合', image:'assets/datasets/droid.jpg',
    license:'CC-BY 4.0', scale:'76k 轨迹 · 350 h', metric:'564 真实场景',
    tags:['野外采集','π0 微调','in-the-wild'],
    desc:'18 实验室 12 个月联合采集，Franka + ZED + Quest 2 统一硬件。π0 / π0.5 的强，一半要归功于在 DROID 上的微调。',
    href:'https://droid-dataset.github.io/' },
  { id:'LeRobot', name:'LeRobot Hub', org:'HuggingFace + Pollen Robotics',
    type:'社区生态', image:'assets/datasets/lerobot.png',
    license:'多协议', scale:'26,991 个数据集', metric:'HF 第一大类目',
    tags:['社区爆炸','一键上下','SO-101'],
    desc:'ROS 是工程师协议，LeRobot 是 ML + 爱好者协议。GitHub 22.7k stars · ICLR 2026 接收 · 每天新增 96 个数据集。',
    href:'https://github.com/huggingface/lerobot' },
  { id:'RoboMIND', name:'RoboMIND 2.0', org:'国家地方共建具身智能机器人创新中心',
    type:'半学术半国家队', image:'assets/datasets/robomind.png',
    license:'学术免费申请', scale:'31 万 轨迹', metric:'12k 触觉序列',
    tags:['国家队','含触觉','中文场景'],
    desc:'国家数据局认证的"高质量数据集典型案例"。多本体 + 触觉模态，国内中文场景研究首选。',
    href:'https://huggingface.co/datasets/x-humanoid-robomind/RoboMIND' },
  { id:'NVIDIA-GR00T', name:'NVIDIA Physical AI / GR00T', org:'NVIDIA',
    type:'大厂开源', image:'assets/datasets/groot.jpg',
    license:'部分 HuggingFace', scale:'24k 仿真 + 1700h 驾驶', metric:'GR00T 基座训练',
    tags:['合成数据','世界模型','GR00T 基座'],
    desc:'黄仁勋 CES 2025："没有数据，就创造数据"。Cosmos 11 小时合成 78 万轨迹 = 9 个月人工示教。',
    href:'https://github.com/NVIDIA/Isaac-GR00T' },
  { id:'1X-World', name:'1X World Model (1xgpt)', org:'1X Technologies',
    type:'商业开源', image:'assets/datasets/1x.jpg',
    license:'Apache 2.0', scale:'100+ 小时', metric:'EVE 第一视角',
    tags:['商业开源','人形 EGO','世界模型'],
    desc:'少数真开源的商业人形数据集。EVE 机器人第一视角视频，用于世界模型预训练。',
    href:'https://github.com/1x-technologies/1xgpt' },
  { id:'SynGrasp', name:'SynGrasp-1B', org:'银河通用 Galbot',
    type:'商业开源 · 合成', image:'assets/datasets/syngrasp.jpg',
    license:'学术免费', scale:'10 亿帧', metric:'视觉-语言-动作对',
    tags:['合成数据','超大规模','另一条路'],
    desc:'不靠真机走合成路线的极致。10 亿帧 VLA 对，是目前最大的合成数据集。',
    href:'https://galbot.com/' },
  { id:'ALOHA', name:'ALOHA / Mobile ALOHA', org:'Stanford · Tony Zhao',
    type:'学术开源', image:'assets/datasets/aloha.png',
    license:'MIT', scale:'单任务 50 episodes', metric:'ACT 论文配套',
    tags:['ACT 经典','小数据 work','双臂遥操'],
    desc:'"数据焦虑是公司的，不是你的。"每任务 50 条 demo 训出双臂叠衣服、穿鞋带、装拉链。',
    href:'https://github.com/tonyzhaozh/aloha' },
  { id:'Fourier-Action', name:'Fourier ActionNet', org:'傅利叶智能 Fourier',
    type:'商业开源', image:'assets/datasets/fourier.jpg',
    license:'自有协议', scale:'3 万+ 真机', metric:'GR-1/GR-2 全套图纸',
    tags:['国产','人形','开数据 + 开硬件'],
    desc:'国产开源派的硬核样板：不光开数据，连机器人本体的全套图纸都开。',
    href:'https://www.fftai.cn/open-source/17' },
  { id:'RH20T', name:'RH20T', org:'上海交大 · 穹彻智能',
    type:'学术开源', image:'assets/datasets/rh20t.png',
    license:'CC-BY 4.0', scale:'110k 轨迹', metric:'147 任务 · 含触觉',
    tags:['含触觉','多任务','多本体'],
    desc:'稀有的"含触觉"开源数据集。多任务 + 多本体 + 触觉模态，触觉研究者必备。',
    href:'https://rh20t.github.io/' },
  { id:'OpenLoong', name:'OpenLoong 青龙', org:'国地中心 (青龙人形)',
    type:'国家队开源', image:'assets/datasets/openloong.jpg',
    license:'商业可用', scale:'青龙人形机器人', metric:'本体 + 数据双开源',
    tags:['国家队','人形','软硬全开'],
    desc:'国家队牵头的人形机器人完全开源项目。本体设计 + 训练数据 + 控制框架一并开放。',
    href:'https://www.openloong.org.cn/en/projects/openloong' },
];
